spring:
  application:
    name: getsbee
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    elasticsearch:
      repositories:
        enabled: true
      url: ${ELASTICSEARCH_URL}:${ELASTICSEARCH_PORT}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}
kibana:
  url: ${ELASTICSEARCH_URL}:${KIBANA_PORT}
jwt:
  secret: ${JWT_SECRET}
google:
  oidc:
    audience: ${GOOGLE_OIDC_AUDIENCE}
---
spring:
  config:
    activate:
      on-profile: "local"
    import: optional:file:.env-local[.properties]
  jpa:
    show-sql: true

logging:
  level:
    org.elasticsearch: DEBUG
    org.springframework.data.elasticsearch.core: DEBUG
---
spring:
  config:
    activate:
      on-profile: "develop"
    import: optional:file:.env-develop[.properties]
logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  config:
    activate:
      on-profile: "production"
    import: optional:file:.env-production[.properties]